### ISSUE TITLE
[Ошибка]: Fatal error: Uncaught Error: Failed opening required

### ISSUE THREAD

**Issue by UrbanSide** [DevCraftClub/dle_api#7]
### Пользовательское соглашение

- [X] Я прочёл / прочла соглашение и согласен / согласна с ними

### В чём проблема?

Запрос на ендпоинт:
**http://localhost/api/v1/users/auth?x-api-key=ключ**
Выдает:
```
Fatal error: Uncaught Error: Failed opening required
'C:\OSPanel\domains\localhost\api\vendor\composer/../lincanbin/php-pdo-mysql-class/src/PDO.class.php' (include_path='.')
in C:\OSPanel\domains\localhost\api\vendor\composer\autoload_real.php:78
Stack trace:
#0 C:\OSPanel\domains\localhost\api\vendor\composer\autoload_real.php(61):
composerRequirea605d6639370e7e4b9025ac25f5fe7b8()
#1 C:\OSPanel\domains\localhost\api\vendor\autoload.php(7):
ComposerAutoloaderInita605d6639370e7e4b9025ac25f5fe7b8::getLoader()
#2 C:\OSPanel\domains\localhost\api\includes\functions.php(9): include_once('C:\\OSPanel\\doma...')
#3 C:\OSPanel\domains\localhost\api\index.php(28): include_once('C:\\OSPanel\\doma...')
#4 {main}
thrown in C:\OSPanel\domains\localhost\api\vendor\composer\autoload_real.php on line 78
```
Установку делал через Bat файл из инструкции.

### Что ожидали?

Надеялся провести авторизацию пользователя,через дискорд,email,логин и т.п я ввожу в регистрацию через DLE API а вот с авторизацией у них беда.Искал апи и нашел ваше чудесное решение.

P.S заранее прошу прощения за назойливость,но ваше решение может быть спасением для очень многих.Спасибо большое.

### Версия плагина

0.3.2

### Версия DLE

16.x (Default)

### Версия PHP

8.x (Default)

### Скриншоты

![image](https://github.com/DevCraftClub/dle_api/assets/26259129/daa90554-edc5-43b8-ad14-0445b08be59f)

**Comment by Gokujo** [comment]
Столкнулся с другой проблемой. Выпущу сейчас фикс.

[Рекомендую к прочтению](https://documenter.getpostman.com/view/7856564/2s93CLsZ6p)

**Comment by Gokujo** [comment]
https://github.com/DevCraftClub/dle_api/releases/tag/v160.0.33

**Comment by Gokujo** [comment]
Проверил постмэном, проблем быть не должно
![image](https://github.com/DevCraftClub/dle_api/assets/19776684/370cf173-2475-498a-a26e-cc97c0bad358)
